[package]
name = "studio_viewer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
studio_ui.workspace = true
studio_graph.workspace = true
studio_canvas.workspace = true
studio_parser.workspace = true
rfd.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
eframe.workspace = true
egui-wgpu = { workspace = true }
wgpu = { workspace = true }
sysinfo = { workspace = true }
pollster = { workspace = true }
serde = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
